config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  scope '/users/:user_id' do
    resource :profile, only: %i[show update]
    resource :following, only: %i[show]
    resource :follower, only: %i[show]
  end
  
  resources :articles, only: %i[new create index] do
    resources :comments, only: %i[index create destroy]
  end

  resources :timelines, only: %i[index]

  namespace :api, defaults: {format: :json} do
    resource :picture, only: %i[show]
    resources :likes, only: %i[index]
    scope '/articles/:article_id' do
      resource :like, only: %i[create destroy]
    end
    scope '/users/:user_id/profile/' do
      resource :relationship, only: %i[create destroy]
    end
  end

  root to: 'articles#index'
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!, only: %i[update]

  def show
    @user = User.find(params[:user_id])
    @profile = @user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'Update your profile.'
    else
      flash.now[:error] = 'failed to update.'
      render :show
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:avatar)
  end

end

app/views/profiles/show.html.haml
.container.profile
  .avatar
    - if @user == current_user
      = form_with(model: @profile, url: profile_path(current_user), method: 'put', local: true, class: 'none', id: 'profile-post-form') do |f|
        = f.file_field :avatar, id: 'profile-avatar'
        = f.submit
    = image_tag @user.avatar_image, class: 'avatar-img', id: 'display-profile-avatar'
  .counter
    .counter-container
      .counter-number= @user.articles.count
      .counter-title= 'Posts'
    = link_to follower_path(@user) do	
      .counter-container
        .counter-number= @user.followers.count
        .counter-title= 'Followers' 
    = link_to following_path(@user) do
      .counter-container
        .counter-number= @user.followings.count
        .counter-title= 'Followings' 
  .image

= javascript_pack_tag 'profile'
  