config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  scope '/users/:user_id' do
    resource :profile, only: %i[show update]
    resource :following, only: %i[show]
    resource :follower, only: %i[show]
  end
  
  resources :articles, only: %i[new create index] do
    resources :comments, only: %i[index create destroy]
  end

  resources :timelines, only: %i[index]

  namespace :api, defaults: {format: :json} do
    resource :picture, only: %i[show]
    resources :likes, only: %i[index]
    scope '/articles/:article_id' do
      resource :like, only: %i[create destroy]
    end
    scope '/users/:user_id/profile/' do
      resource :relationship, only: %i[create destroy]
    end
  end

  root to: 'articles#index'
end

app/views/commons/_articles.html.haml
.container.article
  .switch
    = link_to articles_path do
      #switch-left= 'New arrivals'
    = link_to timelines_path do
      #switch-right= 'Timelines'  
  - articles.each do |article|
    .child-container
      .header
        = link_to profile_path(article.user_id) do
          = image_tag article.user.avatar_image, class: 'avatar-img'
        .header-content
          %div= article.user.account
          .created-at
            = article.calc_elapsed_days
      .body
        %div{ id: "grid-container-#{article.id}" }
          - pictures_num = article.pictures.length
          - pictures_num.times do |n| 
            = image_tag article.pictures[n], class: 'item', id: "grid-item-#{article.id}-#{n}"
      .footer
        - if signed_in? 
          .icons
            %i{ class: "far fa-heart icons", id: "heart-#{article.id}", article_id: "#{article.id}" }
            = link_to article_comments_path(article) do 
              %i{ class: "far fa-comment icons", id: "comment-#{article.id}" }
            = link_to "https://twitter.com/share?ref_src=twsrc%5Etfw", class:"twitter-share-button", "data-show-count":"false"  do
              %i{ class: "fas fa-share-alt icons" }
            %div
              = count_likes(article)
        %div
          = article.description
= javascript_pack_tag 'article-index'

app/views/commons/_userlist.html.haml
.container.userlist
  - userlist.each do |user|
    .child-container
      = link_to profile_path(user) do
        = image_tag user.avatar_image, class: 'avatar-img'
      = user.account